version: '3'
services:
  mongo:
    image: mongo
    ports:
    - '27037:27017'
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
  frontend:
    build: frontend
    environment:
      - REACT_APP_BACKEND_URI=${REACT_APP_BACKEND_URI}
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - ./frontend:/app
    depends_on:
      - backend
  backend:
    build: backend
    ports:
      - '8080:8080'
    environment:
      - MONGO_URI=${MONGO_URI}
      - TEST_MONGO_URI=${TEST_MONGO_URI}
      - TOKEN_SECRET=${TOKEN_SECRET}
    volumes:
      - /app/node_modules
      - ./backend:/app
